### ISSUE TITLE
Daily build automation test failure

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guide-cors#42]
The recent daily build test automation for this guide has been failing with the following error: 

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.68 s <<< FAILURE! - in it.io.openliberty.guides.cors.CorsIT
[ERROR] testPreflightCorsRequest  Time elapsed: 0.22 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected value for Access-Control-Allow-Max-Age header ==> expected: <10> but was: <null>
	at it.io.openliberty.guides.cors.CorsIT.lambda$checkCorsResponse$0(CorsIT.java:69)
	at it.io.openliberty.guides.cors.CorsIT.checkCorsResponse(CorsIT.java:68)
	at it.io.openliberty.guides.cors.CorsIT.testPreflightCorsRequest(CorsIT.java:59)
```

After some investigation, looks like one of the header name had been changed from `Access-Control-Allow-Max-Age` to `Access-Control-Max-Age` (showed in the following output). 

```
--- Preflight CORS Request - EC ---
Header null = [HTTP/1.1 200 OK]
Header Access-Control-Allow-Origin = [anywebsiteyoulike.com]
Header Access-Control-Allow-Methods = [OPTIONS, DELETE]
Header Access-Control-Allow-Credentials = [true]
Header Content-Length = [0]
**Header Access-Control-Max-Age = [10]**
Header Date = [Thu, 02 Jan 2020 21:07:37 GMT]
Header Content-Language = [en-CA]
Header Access-Control-Allow-Headers = [MyOwnHeader1, MyOwnHeader2]
Header X-Powered-By = [Servlet/4.0]
```

After updating the header name in the `TestData.java`, the test passed.

**Comment by evelinec** [comment]
@gkwan-ibm FYI.

**Comment by evelinec** [comment]
Open issue https://github.com/OpenLiberty/open-liberty/issues/10300.
